// REDUX ACTION TYPES COMMENT
export const ADD_TITLE_COMMENT = "ADD_TITLE_COMMENT";
export const ADD_BODY_COMMENT = "ADD_BODY_COMMENT";

// REDUX ACTION TYPES NEW POST
export const ADD_TITLE_POST = "ADD_TITLE_COMMENT";
export const ADD_BODY_POST = "ADD_BODY_COMMENT";
export const SEND_POST = "SEND_POST";
// const SEND_COMMENT = 'SEND_COMMENT'
